### ISSUE TITLE
Spec file is blank

### ISSUE THREAD

**Issue by lizbur10** [learn-co-curriculum/sinatra-activerecord-setup#10]
The spec file is blank so there are no tests to run/pass

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback @lizbur10 .

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
