### ISSUE TITLE
Students have no introduction to manually setting the SINATRA_ENV when running rake tasks

### ISSUE THREAD

**Issue by rishter** [learn-co-curriculum/sinatra-activerecord-setup#12]
We generally have to manually teach them to run migrations, etc. with `SINATRA_ENV=development`, even though many of our labs enforce using that option to work. This could be a good place to introduce that, as it's our introduction to all things ActiveRecord + Sinatra

**Comment by DanielSeehausen** [comment]
thanks @rishter updated with pr!
