### ISSUE TITLE
Code in config.ru throws errors

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/sinatra-activerecord-setup#14]
**config.ru**
This starter code throws errors in server: 

require './config/environment'
if ActiveRecord::Base.connection.migration_context.needs_migration?
  raise 'Migrations are pending. Run `rake db:migrate` to resolve the issue.'
end
run ApplicationController

NoMethodError: undefined method `migration_context' for #<ActiveRecord::ConnectionAdapters::SQLite3Adapter:0x007ff66dd3be48> Did you mean? migration_keys

**Change to:  
require './config/environment'

if ActiveRecord::Migrator.needs_migration?
  raise 'Migrations are pending. Run `rake db:migrate SINATRA_ENV=test` to resolve the issue.'
end

run ApplicationController**

**Comment by cjbrock** [comment]
Hey @justinddaniel!

I'm pretty sure you just need to migrate your database, but try hopping over to Ask A Question. They should be able to help you out!

// <3 Corinna
