### ISSUE TITLE
Solution does not match provided code

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/sinatra-activerecord-setup#15]
Hey there, I'm following along with the directions from this lab, and unfortunately when I enter the provided code into the rakefile, it gives me this error: 
```rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/Users/helloamandamurphy/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/Users/helloamandamurphy/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
/Users/helloamandamurphy/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
```

That's fine and dandy, but when I went to look at the solution to see if I had added it in the wrong place, I noticed the solution code provided on the repo is not the solution for the lab and is missing the code provided in the walkthrough. There is no rakefile in the solution and the gems have not been updated. I know there is no spec for the lab, but I still want to be able to double check that I'm following the lab properly.

**Comment by maxwellbenton** [comment]
Hi @helloamandamurphy,

Thank you for spotting this and providing feedback. We've updated this lesson's instructions, support files to ensure it is functioning as it should, and made sure that the solution now correctly aligns with the end result of the instructions. The solution now contains a rakefile and updated gems.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
