### ISSUE TITLE
IDE is not responding to control+C when server is on.

### ISSUE THREAD

**Issue by lauratravin** [learn-co-curriculum/sinatra-activerecord-setup#17]
Hello,
I can't log off the server using control + C. It is like the IDE is dead, no response. Only way is close the IDE and start again. 
Shotgun/WEBrick on http://0.0.0.0:9393/
[2019-04-10 19:16:28] INFO  WEBrick 1.4.2
[2019-04-10 19:16:28] INFO  ruby 2.6.1 (2019-01-30) [x86_64-linux]
[2019-04-10 19:16:28] INFO  WEBrick::HTTPServer#start: pid=16501 port=42882
D, [2019-04-10T19:16:38.262414 #17179] DEBUG -- :    (0.2ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
D, [2019-04-10T19:16:38.272245 #17179] DEBUG -- :   Article Load (0.2ms)  SELECT "articles".* FROM "articles"
71.190.142.19 - - [10/Apr/2019:19:16:38 +0000] "GET / HTTP/1.1" 200 155 0.0077
D, [2019-04-10T19:16:42.922256 #17511] DEBUG -- :    (0.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
71.190.142.19 - - [10/Apr/2019:19:16:42 +0000] "GET /new HTTP/1.1" 404 536 0.0039
D, [2019-04-10T19:16:43.855807 #17565] DEBUG -- :    (0.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
71.190.142.19 - - [10/Apr/2019:19:16:43 +0000] "GET /__sinatra__/404.png HTTP/1.1" 200 18893 0.0061
D, [2019-04-10T19:16:59.862456 #17982] DEBUG -- :    (0.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
71.190.142.19 - - [10/Apr/2019:19:16:59 +0000] "GET /articles/new HTTP/1.1" 200 274 0.0060
D, [2019-04-10T19:17:28.961154 #18057] DEBUG -- :    (0.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
71.190.142.19 - - [10/Apr/2019:19:17:28 +0000] "GET /articles/new HTTP/1.1" 200 276 0.0061
D, [2019-04-10T19:18:26.881367 #18134] DEBUG -- :    (0.2ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
71.190.142.19 - - [10/Apr/2019:19:18:26 +0000] "GET /articles/new HTTP/1.1" 200 302 0.0062
D, [2019-04-10T19:18:36.004944 #18168] DEBUG -- :    (0.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
71.190.142.19 - - [10/Apr/2019:19:18:36 +0000] "GET /articles?title=zaza&content=dkjlfsajflkd&submit=Submit HTTP/1.1" 404 541 0.0039
D, [2019-04-10T19:20:45.146605 #18245] DEBUG -- :    (0.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
71.190.142.19 - - [10/Apr/2019:19:20:45 +0000] "GET /articles?title=zaza&content=dkjlfsajflkd&submit=Submit HTTP/1.1" 404 541 0.0041
D, [2019-04-10T19:20:46.107568 #18278] DEBUG -- :    (0.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
71.190.142.19 - - [10/Apr/2019:19:20:46 +0000] "GET /__sinatra__/404.png HTTP/1.1" 304 - 0.0047
c^C
^Cccquit
^C^C^C^C^C
^Y
^C^C^C
quit
^C

**Comment by Sdcrouse** [comment]
Hi. Fellow student here. I've encountered a similar problem on other lessons, especially in the Forms section. I don't know how consistently it happens, though. This is an issue that should probably be sent to bugs@learn.co, since it's not limited to just this lesson.

**Comment by drakeltheryuujin** [comment]
Yes this would be something the support team can help you with. You can reach them at support@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.
