### ISSUE TITLE
rake does not work

### ISSUE THREAD

**Issue by tan-nate** [learn-co-curriculum/sinatra-activerecord-setup#18]
despite adding the necessary gems in the Gemfile and setting the database in environment.rb, rake does not install. I get teh following error:

`/usr/local/rvm/gems/ruby-2.6.1/gems/activesupport-4.2.5/lib/active_support/core_ext/object/dupli
cable.rb:85: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
rake aborted!
Gem::LoadError: Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 's
qlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).`

`Caused by:
Gem::LoadError: can't activate sqlite3 (~> 1.3.6), already activated sqlite3-1.4.1. Make sure al
l dependencies are added to Gemfile.`

**Comment by maxwellbenton** [comment]
Hi @tan-nate,

Thank you for providing feedback on this issue. We were able to recreate the problem of rake not functioning and were able to solve it by updating the ActiveRecord version. We've also updated the Readme instructions and solution and believe this issue should now be resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
