### ISSUE TITLE
This directory doesn't have any specs in it

### ISSUE THREAD

**Issue by m-gamao** [learn-co-curriculum/sinatra-activerecord-setup#19]
Can you please put the specs file into the lab directory so that I can mark this lab as completed?  See the below.  thanks!

[17:43:10] (master) sinatra-activerecord-setup-v-000
// ♥ learn
This directory doesn't appear to have any specs in it.
[17:44

**Comment by drakeltheryuujin** [comment]
Hi there, 
This is not a lab and does not need specs to be run to mark as completed. 

This sounds like a problem with the Learn platform. Our product team can help you with this. You can reach them at support@learn.co.

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.
