### ISSUE TITLE
fill out spec

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/sinatra-activerecord-setup#3]
test the existence of the migrations and that they actually do the right thing. Here is an example of testing migrations https://github.com/learn-co-curriculum/writing-migrations/blob/master/spec/02_add_column_spec.rb

**Comment by victhevenot** [comment]
those tests require a lot of setup in config/environment -- WAY more than we walk the students through in this walkthrough. Not possible to write migration tests without a lot of configuration settings @jmburges

**Comment by victhevenot** [comment]
closing per conversation with Joe about too many configurations for tests to be useful
